version: "3.3"

services:
  database:
    container_name: petdjango_database
    image: postgres
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=petpro
      - POSTGRES_USER=petpro
    ports:
      - 5437:5432